In [1]:
# First import the library
import pyrealsense2 as rs
import numpy as np
import cv2

# Create a context object. This object owns the handles to all connected realsense devices
pipeline = rs.pipeline()
pipeline.start()

while True:
    # This call waits until a new coherent set of frames is available on a device
    # Calls to get_frame_data(...) and get_frame_timestamp(...) on a device will return stable values until wait_for_frames(...) is called
    frames = pipeline.wait_for_frames()
    depth = frames.get_color_frame()
    depth_data = depth.as_frame().get_data()
    np_image = np.asanyarray(depth_data)
    
    cv2.imshow('object detection2',np_image[:,:,[2,1,0]])
#     frames= pipeline.wait_for_frames()
#     for f in frames:
#       print(f.profile)
        
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
        
        

KeyboardInterrupt: 

In [13]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[0:-1])

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
x = np.array([[1, 2, 2.5],[1, 2, 2.5]])
x.astype(int)

a=3
print(a)

array([[1, 2, 2],
       [1, 2, 2]])

In [1]:
# First import the library
import pyrealsense2 as rs
import numpy as np
import cv2


clip_disp_x = 0
clip_disp_y = 0

# Create a context object. This object owns the handles to all connected realsense devices
pipeline = rs.pipeline()
pipeline.start()

frames = pipeline.wait_for_frames()
#get depth影像
depth = frames.get_depth_frame() 
depth_image_data = depth.as_frame().get_data()
depth_image = np.asanyarray(depth_image_data)
#計算depth影像對應至rgb影像的clip
clip_box = [100,-100,290,-330]

while True:
    # This call waits until a new coherent set of frames is available on a device
    # Calls to get_frame_data(...) and get_frame_timestamp(...) on a device will return stable values until wait_for_frames(...) is called
    frames = pipeline.wait_for_frames()
    
    #get rgb影像
    image_frame = frames.get_color_frame()
    image_data = image_frame.as_frame().get_data()
    image = np.asanyarray(image_data)
    
    #get depth影像
    depth = frames.get_depth_frame() 
    depth_image_data = depth.as_frame().get_data()
    depth_image = np.asanyarray(depth_image_data)
    depth_image = depth_image[(int)(clip_box[0]):(int)(clip_box[1]),(int)(clip_box[2]):(int)(clip_box[3])]
    depth_image = cv2.resize(depth_image, (640, 480), interpolation=cv2.INTER_CUBIC)
    depth_image=depth_image/30
    depth_image.astype(np.uint8)
    thresh=cv2.inRange(depth_image,0,200)
    print(thresh.shape);
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))  
    eroded = cv2.erode(thresh,kernel)
    kernel2 = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))  
    dilated = cv2.dilate(eroded,kernel2)
    
    bright_mask = np.zeros(image.shape);
    bright_mask.fill(50)
    bright_mask = bright_mask.astype(np.uint8);
    bright_mask = cv2.bitwise_and(bright_mask, bright_mask, mask=dilated)
    np.clip(bright_mask, 1, 8)
    
    masked_data = cv2.bitwise_and(image, image, mask=dilated)
    image = image.astype(int)
    bright_mask = bright_mask.astype(int)
    image=image-bright_mask;
    image = np.clip(image, 0, 255)
    image = image.astype(np.uint8);

    
     
    cv2.imshow('object detection2',image[:,:,[2,1,0]])
#     frames= pipeline.wait_for_frames()
#     for f in frames:
#       print(f.profile)
        
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
        
        

(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)
(480, 640)

KeyboardInterrupt: 

In [ ]:
def mathc_img(image,Target,value): 
    import cv2 
    import numpy as np 
    img_rgb = cv2.imread(image) 
    img_gray= cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY) 
    template = cv2.imread(Target,0) 
    w, h = template.shape[::-1]
    res = cv2.matchTemplate(img_gray,template,cv2.TM_CCOEFF_NORMED) 
    threshold = value 
    loc = np.where( res >= threshold) 
    for pt in zip(*loc[::-1]): 
        cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (7,249,151), 2) 
        cv2.imshow('Detected',img_rgb) 
        cv2.waitKey(0)
        cv2.destroyAllWindows()

image=('photo.jpg')
Target=('face.jpg')
value=0.9
mathc_img(image,Target,value)

In [15]:
a=[(1,2),(3,5),(3,52),(3,51)]
print(a[int(len(a)/2)])


(3, 52)


In [22]:
a=[(1,2),(3,3)]
b=(3,4)

sum(a)

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [3]:

import cv2
import numpy as np 
image = cv2.imread('photo.jpg')

cv2.circle(image,(10,50), 5, (0,0,255), -1)
subimg = image[50:100,10:100]
cv2.imshow("Original", subimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import numpy as np 
res = np.random.rand(3,5)
print(res.shape)
print(res)
loc = np.where( res >= 0.6)
print(loc)



(3, 5)
[[ 0.2221422   0.81092111  0.66798638  0.86865806  0.29436116]
 [ 0.13180667  0.0826481   0.7589162   0.89070312  0.15794417]
 [ 0.26051594  0.81182946  0.0869471   0.62295451  0.80975236]]
(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64), array([1, 2, 3, 2, 3, 1, 3, 4], dtype=int64))
